version: '3.8'

services:
  flower:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: celery -A app.celery flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0